apiVersion: v1
kind: Secret
metadata:
  name: hdc-toolkit-secrets
  namespace: hd-compute-toolkit
  labels:
    app.kubernetes.io/name: hd-compute-toolkit
    app.kubernetes.io/component: config
type: Opaque
data:
  # Database credentials (base64 encoded)
  # Default values - should be replaced in production
  POSTGRES_USER: aGRjX3VzZXI=          # hdc_user
  POSTGRES_PASSWORD: aGRjX3Bhc3N3b3Jk # hdc_password
  
  # Redis password (if needed)
  REDIS_PASSWORD: ""
  
  # API keys and secrets (add as needed)
  # HDC_API_SECRET: <base64-encoded-secret>
  # HDC_JWT_SECRET: <base64-encoded-jwt-secret>
  
  # Third-party service credentials
  # MLFLOW_TRACKING_TOKEN: <base64-encoded-token>
  # MONITORING_API_KEY: <base64-encoded-key>