name: Bug Report
description: File a bug report to help us improve HD-Compute-Toolkit
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import hd_compute...
        2. Call function...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Minimal code sample
      description: Please provide a minimal code sample that reproduces the issue
      render: python
      placeholder: |
        import torch
        from hd_compute import HDCompute
        
        # Minimal code to reproduce the issue

  - type: dropdown
    id: backend
    attributes:
      label: Backend
      description: Which backend are you using?
      options:
        - PyTorch
        - JAX
        - Pure Python
        - Multiple backends
        - Not sure
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: HD-Compute-Toolkit version
      description: What version of HD-Compute-Toolkit are you running?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment:
        - OS (Linux, macOS, Windows)
        - Python version
        - PyTorch/JAX version (if applicable)
        - CUDA/GPU information (if using GPU)
      placeholder: |
        - OS: Ubuntu 22.04
        - Python: 3.9.0
        - PyTorch: 2.0.0
        - CUDA: 11.8
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error logs
      description: Please copy and paste any relevant error output or logs
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here