name: Feature Request
description: Suggest a new feature or enhancement for HD-Compute-Toolkit
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: Is your feature request related to a problem? Please describe the use case.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Core HDC operations
        - PyTorch backend
        - JAX backend
        - Hardware acceleration (FPGA/Vulkan)
        - Memory structures
        - Applications
        - Performance/benchmarking
        - Documentation
        - API/interface
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - nice to have
        - Medium - would be helpful
        - High - blocking my work
        - Critical - prevents adoption
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: A workaround could be...

  - type: textarea
    id: research-impact
    attributes:
      label: Research impact
      description: How would this feature benefit the HDC research community?
      placeholder: This would enable research into...

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation ideas
      description: If you have ideas about how this could be implemented, please share them.
      placeholder: This could be implemented by...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request here.