apiVersion: apps/v1
kind: Deployment
metadata:
  name: hd-compute-api
  namespace: hd-compute
  labels:
    app: hd-compute-api
    version: v1.0.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hd-compute-api
  template:
    metadata:
      labels:
        app: hd-compute-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: hd-compute-api
        image: hd-compute-toolkit:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: HDC_ENV
          value: "production"
        - name: HDC_WORKERS
          value: "4"
        - name: HDC_MAX_DIMENSION
          value: "50000"
        - name: HDC_CACHE_SIZE
          valueFrom:
            configMapKeyRef:
              name: hd-compute-config
              key: cache_size
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: hd-compute-secrets
              key: database_url
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: hd-compute-config
              key: redis_url
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: hdc-data
          mountPath: /app/data
        - name: hdc-config
          mountPath: /app/config
          readOnly: true
        - name: hdc-logs
          mountPath: /app/logs
      volumes:
      - name: hdc-data
        persistentVolumeClaim:
          claimName: hdc-data-pvc
      - name: hdc-config
        configMap:
          name: hd-compute-config
      - name: hdc-logs
        emptyDir: {}
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
      - key: "node-role.kubernetes.io/compute"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - hd-compute-api
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: hd-compute-api-service
  namespace: hd-compute
  labels:
    app: hd-compute-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: hd-compute-api
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hd-compute-api-hpa
  namespace: hd-compute
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hd-compute-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
