# HD Compute Toolkit - Staging Configuration
# Staging environment with production-like settings but more debugging

application:
  name: "HD-Compute-Toolkit"
  version: "1.0.0"
  environment: "staging"
  debug: true
  
server:
  host: "0.0.0.0"
  port: 8000
  workers: 2
  max_connections: 500
  timeout: 60
  keepalive: 75
  
logging:
  level: "DEBUG"
  format: "json"
  output: "stdout"
  audit_enabled: true
  audit_file: "/app/logs/audit.log"
  max_size: "50MB"
  backup_count: 5
  
database:
  host: "postgres-service"
  port: 5432
  database: "hdc_experiments_staging"
  username: "${POSTGRES_USER}"
  password: "${POSTGRES_PASSWORD}"
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 3600
  ssl_mode: "prefer"
  
redis:
  host: "redis-service"
  port: 6379
  password: "${REDIS_PASSWORD}"
  db: 1
  max_connections: 10
  socket_timeout: 5
  socket_connect_timeout: 5
  health_check_interval: 30
  
hdc:
  default_device: "cpu"
  dimension: 1000
  cache_enabled: true
  cache_max_size: 500
  cache_ttl: 1800
  enable_profiling: true
  benchmark_mode: false
  
performance:
  max_workers: 2
  batch_size: 50
  memory_limit: "1GB"
  cpu_limit: "1000m"
  enable_optimization: true
  
security:
  enable_security_scan: true
  strict_input_validation: true
  rate_limit_enabled: true
  rate_limit_requests_per_minute: 500
  rate_limit_burst: 50
  cors_enabled: true
  cors_origins: ["https://staging.your-domain.com", "http://localhost:3000"]
  csrf_protection: true
  content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'"
  
compliance:
  gdpr_enabled: true
  audit_logging: true
  data_retention_days: 90  # Shorter retention for staging
  audit_retention_days: 90
  privacy_mode: true
  anonymization_enabled: false  # Disabled for testing
  
internationalization:
  enabled: true
  default_locale: "en"
  supported_locales: ["en", "es", "fr", "de"]
  fallback_locale: "en"
  
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_path: "/health"
  ready_check_path: "/ready"
  metrics_path: "/metrics"
  
storage:
  data_dir: "/app/data"
  log_dir: "/app/logs"
  models_dir: "/app/models"
  temp_dir: "/tmp"
  backup_enabled: true
  backup_schedule: "0 4 * * *"  # Daily at 4 AM
  
features:
  api_enabled: true
  web_ui_enabled: true  # Enabled for testing
  admin_panel_enabled: true
  debug_endpoints_enabled: true
  
limits:
  max_request_size: "50MB"
  max_file_size: "25MB"
  max_memory_per_request: "250MB"
  max_processing_time: 180  # seconds